//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingICT_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public int ID { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int StopsOutgoing { get; set; }
        public int StopsIngoing { get; set; }
        public string AdultAvailabilityIngoing { get; set; }
        public string ChildrenAvailabilityIngoing { get; set; }
        public string InfantsAvailabilityIngoing { get; set; }
        public string SeniorsAvailabilityIngoing { get; set; }
        public string AdultAvailabilityOutgoing { get; set; }
        public string ChildrenAvailabilityOutgoing { get; set; }
        public string InfantsAvailabilityOutgoing { get; set; }
        public string SeniorsAvailabilityOutgoing { get; set; }
        public double Price { get; set; }
        public string Currency { get; set; }
    }
}
