//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingICT_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public int ID { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int StopsOutgoing { get; set; }
        public int StopsIngoing { get; set; }
        public Nullable<int> AdultAvailabilityIngoing { get; set; }
        public Nullable<int> ChildrenAvailabilityIngoing { get; set; }
        public Nullable<int> InfantsAvailabilityIngoing { get; set; }
        public Nullable<int> SeniorsAvailabilityIngoing { get; set; }
        public Nullable<int> AdultAvailabilityOutgoing { get; set; }
        public Nullable<int> ChildrenAvailabilityOutgoing { get; set; }
        public Nullable<int> InfantsAvailabilityOutgoing { get; set; }
        public Nullable<int> SeniorsAvailabilityOutgoing { get; set; }
        public decimal Price { get; set; }
        public string Currency { get; set; }
    }
}
