//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingICT_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iata_airport_codes
    {
        public int ID { get; set; }
        public string Airport { get; set; }
        public string Code { get; set; }
    }
}
